import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  headerSafeArea: {
    backgroundColor: 'transparent',
  },
  headerGradient: {
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#D4A514',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  headerOrb1: {
    position: 'absolute',
    top: -40,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerOrb2: {
    position: 'absolute',
    top: 20,
    left: -80,
    width: 250,
    height: 120,
    borderRadius: 150,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '700',
    color: '#1A3A0F',
  },
  saveButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentScroll: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  titleInput: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderWidth: 1,
    borderColor: '#2D5A1B',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#1A2E0F',
    marginBottom: 4,
  },
  titleHint: {
    fontSize: 11,
    color: '#4A7C2A',
    fontStyle: 'italic',
    marginBottom: 14,
  },
  tabsRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 12,
  },
  tabChip: {
    flex: 1,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(45,90,27,0.10)',
  },
  activeTabChip: {
    backgroundColor: '#2D5A1B',
    borderColor: '#2D5A1B',
  },
  tabText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#4A7C2A',
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  
  textInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    fontSize: 15,
    color: '#1A2E0F',
    lineHeight: 24,
    minHeight: 200,
    textAlignVertical: 'top',
    marginTop: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  placeholderContainer: {
    paddingVertical: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderText: {
    fontSize: 14,
    color: '#888888',
    marginTop: 12,
  },
  capsuleSection: {
    marginTop: 20,
    marginBottom: 16,
  },
  capsuleToggle: {
    backgroundColor: 'rgba(245,220,50,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(184,134,11,0.28)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  capsuleToggleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  capsuleToggleTextColumn: {
    marginLeft: 8,
  },
  capsuleTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#5A3E00',
  },
  capsuleSubtitle: {
    fontSize: 11,
    color: '#B8860B',
  },
  switchTrack: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(45,90,27,0.20)',
    paddingHorizontal: 2,
    justifyContent: 'center',
  },
  switchTrackActive: {
    backgroundColor: '#2D5A1B',
  },
  switchThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  capsuleOptions: {
    marginTop: 10,
    overflow: 'hidden',
  },
  durationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  durationChip: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    marginHorizontal: 3,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(184,134,11,0.20)',
  },
  activeDurationChip: {
    backgroundColor: 'rgba(245,220,50,0.28)',
    borderWidth: 1.5,
    borderColor: 'rgba(184,134,11,0.48)',
  },
  durationChipText: {
    fontSize: 13,
    color: '#B8860B',
  },
  activeDurationChipText: {
    color: '#5A3E00',
    fontWeight: '700',
  },
  unlockDateText: {
    fontSize: 11,
    color: '#B8860B',
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 6,
  },
  saveCapsuleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2D5A1B',
    borderRadius: 25,
    paddingVertical: 14,
    marginTop: 20,
    marginBottom: 24,
  },
  saveCapsuleText: {
    fontSize: 15,
    fontWeight: '600',
    color: 'white',
    marginLeft: 8,
  },
  // Formatting Toolbar
  toolbarContainer: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 8,
    gap: 4,
    alignItems: 'center',
  },
  toolbarButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  activeToolbarButton: {
    backgroundColor: 'rgba(45,90,27,0.12)',
  },
  toolbarDivider: {
    width: 1,
    height: 20,
    backgroundColor: 'rgba(0,0,0,0.1)',
    marginHorizontal: 4,
  },
  boldIcon: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1A2E0F',
  },
  italicIcon: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#1A2E0F',
  },
  underlineIcon: {
    fontSize: 14,
    textDecorationLine: 'underline',
    color: '#1A2E0F',
  },
  strikeIcon: {
    fontSize: 14,
    textDecorationLine: 'line-through',
    color: '#1A2E0F',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  unsavedModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    marginHorizontal: 32,
    alignItems: 'center',
    width: '85%',
  },
  unsavedModalTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '700',
    color: '#1A2E0F',
    marginBottom: 6,
    textAlign: 'center',
  },
  unsavedModalMessage: {
    fontSize: 13,
    color: '#888888',
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 18,
  },
  unsavedModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 8,
  },
  unsavedCancelBtn: {
    flex: 1.2,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: 'rgba(0,0,0,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unsavedCancelText: {
    color: '#888888',
    fontSize: 12,
    fontWeight: '600',
  },
  unsavedDiscardBtn: {
    flex: 1,
    backgroundColor: '#E85555',
    borderRadius: 25,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unsavedDiscardText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  unsavedSaveBtn: {
    flex: 1,
    backgroundColor: '#2D5A1B',
    borderRadius: 25,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unsavedSaveText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
});
