import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  headerGradient: {
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#D4A514',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  headerOrb1: {
    position: 'absolute',
    top: -40,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerOrb2: {
    position: 'absolute',
    top: 20,
    left: -80,
    width: 250,
    height: 120,
    borderRadius: 150,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '700',
    color: '#1A3A0F',
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(245,220,50,0.20)',
    borderWidth: 1.5,
    borderColor: 'rgba(184,134,11,0.30)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2D5A1B',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  newEntryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245,220,50,0.18)',
    borderWidth: 1.5,
    borderColor: 'rgba(184,134,11,0.35)',
    borderRadius: 14,
    paddingVertical: 14,
    marginBottom: 20,
  },
  newEntryBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2D5A1B',
    marginLeft: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: 'serif',
    fontSize: 16,
    fontWeight: '700',
    color: '#1A2E0F',
  },
  searchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  searchText: {
    fontSize: 12,
    color: '#4A7C2A',
    fontWeight: '600',
  },
  emptyState: {
    paddingVertical: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    color: '#1A2E0F',
    marginTop: 12,
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#888888',
    marginTop: 6,
    textAlign: 'center',
  },
  // Entry Card Styles
  card: {
    backgroundColor: 'rgba(255,255,255,0.75)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.92)',
    borderRadius: 16,
    padding: 12,
    marginBottom: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  capsuleCard: {
    borderLeftWidth: 3,
    borderLeftColor: '#B8860B',
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  cardTitleWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  cardTitle: {
    fontFamily: 'serif',
    fontSize: 15,
    fontWeight: '700',
    color: '#1A2E0F',
  },
  cardPreview: {
    fontSize: 12,
    color: '#888888',
    marginTop: 2,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  dateText: {
    fontSize: 11,
    color: '#888888',
  },
  capsuleBadge: {
    backgroundColor: 'rgba(184,134,11,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(184,134,11,0.30)',
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  capsuleBadgeText: {
    fontSize: 10,
    color: '#7A5800',
    fontWeight: '700',
  },
  // Actions Row
  actionsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 4,
    paddingBottom: 8,
    marginTop: -4,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(45,90,27,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(45,90,27,0.15)',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    gap: 4,
  },
  actionText: {
    fontSize: 13,
    color: '#2D5A1B',
    fontWeight: '600',
  },
  actionBtnDisabled: {
    backgroundColor: 'rgba(0,0,0,0.04)',
    borderColor: 'rgba(0,0,0,0.08)',
  },
  actionTextDisabled: {
    color: '#AAAAAA',
  },
  deleteBtn: {
    backgroundColor: 'rgba(232,85,85,0.08)',
    borderColor: 'rgba(232,85,85,0.15)',
  },
  deleteText: {
    color: '#E85555',
  },
  // Modal Styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    marginHorizontal: 32,
    width: '80%',
  },
  modalTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '700',
    color: '#1A2E0F',
    marginBottom: 6,
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#888888',
    marginBottom: 24,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalCancel: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: 'rgba(0,0,0,0.05)',
    alignItems: 'center',
  },
  modalCancelText: {
    color: '#888888',
    fontSize: 14,
    fontWeight: '600',
  },
  modalDelete: {
    flex: 1,
    backgroundColor: '#E85555',
    borderRadius: 25,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalDeleteText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
});
