import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  headerSafeArea: {
    backgroundColor: 'rgba(255,255,255,0.62)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.82)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderWidth: 1,
    borderColor: 'rgba(45,90,27,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderWidth: 1,
    borderColor: 'rgba(45,90,27,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 16,
    fontWeight: '700',
    color: '#1A2E0F',
  },
  contentScroll: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 40,
  },
  // Locked Capsule State
  lockedContainer: {
    paddingVertical: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockedTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    color: '#5A3E00',
    marginTop: 12,
    textAlign: 'center',
  },
  lockedSubtitle: {
    fontSize: 13,
    color: '#B8860B',
    marginTop: 6,
    textAlign: 'center',
  },
  lockedFooter: {
    fontSize: 12,
    color: '#888888',
    marginTop: 4,
    textAlign: 'center',
  },
  // Unlocked Banner
  unlockedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245,220,50,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(184,134,11,0.28)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 16,
    gap: 8,
  },
  bannerLabel: {
    fontSize: 13,
    color: '#7A5800',
    fontWeight: '600',
  },
  bannerDate: {
    fontSize: 11,
    color: '#B8860B',
  },
  // Normal Content
  title: {
    fontFamily: 'serif',
    fontSize: 22,
    fontWeight: '700',
    color: '#1A2E0F',
    marginBottom: 8,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  spaceTag: {
    backgroundColor: 'rgba(45,90,27,0.08)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  spaceTagText: {
    fontSize: 11,
    color: '#2D5A1B',
    fontWeight: '600',
  },
  metaDate: {
    fontSize: 11,
    color: '#888888',
  },
  editedText: {
    fontSize: 11,
    color: '#888888',
    fontStyle: 'italic',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(45,90,27,0.08)',
    marginVertical: 16,
  },
  bodyContent: {
    fontSize: 16,
    color: '#333333',
    lineHeight: 26,
  },
  // Audio Player Styles
  // audioCard: {
  //   backgroundColor: 'rgba(255,255,255,0.75)',
  //   borderRadius: 12,
  //   padding: 12,
  //   marginBottom: 8,
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   shadowColor: '#2D5A1B',
  //   shadowOffset: { width: 0, height: 2 },
  //   shadowOpacity: 0.06,
  //   shadowRadius: 14,
  // },
  audioCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  playPauseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(45,90,27,0.10)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  audioInfo: {
    flex: 1,
  },
  audioName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A2E0F',
  },
  audioDuration: {
    fontSize: 11,
    color: '#888888',
  },
  // Image Grid Styles
  imageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginTop: 12,
  },
  gridImage: {
    width: (width - 48) / 2,
    height: 140,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
  },
  imageCaption: {
    fontSize: 14,
    color: '#4A4A4A',
    fontStyle: 'italic',
    marginTop: 12,
    lineHeight: 20,
  },
  doodleImage: {
    width: width - 32,
    height: 280,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  placeholderContainer: {
    width: width - 32,
    height: 200,
    borderRadius: 14,
    backgroundColor: 'rgba(45,90,27,0.03)',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(45,90,27,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  placeholderText: {
    fontSize: 14,
    color: '#888888',
    marginTop: 8,
  },
});
