import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  topSafe: {
    backgroundColor: 'transparent',
  },
  headerGradient: {
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#D4A514',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  headerOrb1: {
    position: 'absolute',
    top: -40,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerOrb2: {
    position: 'absolute',
    top: 20,
    left: -80,
    width: 250,
    height: 120,
    borderRadius: 150,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  headerSafeArea: {
    backgroundColor: 'transparent',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 9,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerLeft: {
    width: 36,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
  },
  avatarText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2D5A1B',
  },
  personName: {
    fontFamily: 'serif',
    fontSize: 16,
    fontWeight: '700',
    color: '#1A3A0F',
    marginLeft: 8,
  },
  headerRight: {
    width: 60,
    alignItems: 'flex-end',
  },
  limitBadge: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    borderRadius: 12,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  limitText: {
    fontSize: 11,
    color: '#1A3A0F',
    fontWeight: '700',
  },
  // Guided Reflection Banner
  banner: {
    backgroundColor: 'rgba(245,220,50,0.10)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(184,134,11,0.15)',
  },
  bannerText: {
    fontSize: 11,
    color: '#B8860B',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  // Messages Area
  messagesArea: {
    flex: 1,
  },
  flatListContent: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 20,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(45,90,27,0.12)',
    borderRadius: 16,
    borderBottomRightRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
    maxWidth: '75%',
    marginBottom: 8,
  },
  userText: {
    fontSize: 14,
    color: '#1A2E0F',
    lineHeight: 20,
  },
  aiBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
    maxWidth: '75%',
    marginBottom: 8,
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  aiText: {
    fontSize: 14,
    color: '#1A2E0F',
    lineHeight: 20,
  },
  // Typing Indicator
  typingIndicator: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#2D5A1B',
    marginHorizontal: 2,
  },
  // Input Area
  inputSafeArea: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(45,90,27,0.08)',
  },
  inputContainer: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textInput: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 16,
    fontSize: 14,
    color: '#1A2E0F',
    maxHeight: 100,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  sendBtnActive: {
    backgroundColor: '#1A3A0F',
  },
  sendBtnInactive: {
    backgroundColor: 'rgba(45,90,27,0.15)',
  },
  keyboardView: {
    flex: 1,
  },
  messagesList: {
    flex: 1,
  },
  inputArea: {
    borderTopWidth: 0,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  typingText: {
    fontSize: 14,
    color: '#888888',
    fontStyle: 'italic',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  limitBadgeEmpty: {
    backgroundColor: 'rgba(232,85,85,0.08)',
    borderRadius: 12,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  limitTextEmpty: {
    fontSize: 11,
    color: '#E85555',
    fontWeight: '600',
  },
  limitReached: {
    backgroundColor: 'rgba(45,90,27,0.06)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  limitReachedText: {
    fontSize: 13,
    color: '#2D5A1B',
    textAlign: 'center',
  },
});
