import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  headerSafeArea: {
    backgroundColor: 'transparent',
  },
  headerGradient: {
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#D4A514',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  headerOrb1: {
    position: 'absolute',
    top: -40,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerOrb2: {
    position: 'absolute',
    top: 20,
    left: -80,
    width: 250,
    height: 120,
    borderRadius: 150,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 9,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerLeft: {
    width: 36,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '700',
    color: '#1A3A0F',
  },
  headerRight: {
    width: 48,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  stepText: {
    fontSize: 13,
    color: '#1A3A0F',
    fontWeight: '700',
  },
  scrollViewContent: {
    paddingBottom: 40,
  },
  progressBarContainer: {
    marginHorizontal: 16,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  stepCol: {
    flex: 1,
    alignItems: 'center',
  },
  stepPill: {
    width: '100%',
    height: 6,
    borderRadius: 3,
  },
  stepPillCompleted: {
    backgroundColor: '#2D5A1B',
  },
  stepPillCurrent: {
    backgroundColor: '#2D5A1B',
  },
  stepPillFuture: {
    backgroundColor: 'rgba(45,90,27,0.15)',
  },
  dotIndicatorContainer: {
    height: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
  },
  stepActiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#2D5A1B',
  },
  stepLabel: {
    fontSize: 9,
    color: '#888888',
    textAlign: 'center',
    marginTop: 6,
  },
  sectionHeaderCard: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: 'rgba(45,90,27,0.07)',
    borderRadius: 12,
    padding: 12,
  },
  sectionHeaderTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2D5A1B',
  },
  sectionHeaderSubtitle: {
    fontSize: 12,
    color: '#4A7C2A',
    marginTop: 2,
    fontStyle: 'italic',
  },
  descriptionText: {
    marginHorizontal: 16,
    marginTop: 8,
    fontSize: 13,
    color: '#888888',
    lineHeight: 18,
    marginBottom: 8,
  },
  questionBlock: {
    marginHorizontal: 16,
    marginTop: 16,
  },
  questionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A2E0F',
    marginBottom: 8,
  },
  questionSublabel: {
    fontSize: 11,
    color: '#888888',
    marginTop: -4,
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: '#1A2E0F',
    textAlignVertical: 'top',
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  // Option Buttons
  optionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(45,90,27,0.12)',
    padding: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionCardSelected: {
    backgroundColor: 'rgba(45,90,27,0.08)',
    borderColor: '#2D5A1B',
    borderWidth: 1.5,
  },
  optionText: {
    fontSize: 14,
    color: '#1A2E0F',
    fontWeight: '400',
    flex: 1,
    marginRight: 8,
  },
  optionTextSelected: {
    color: '#2D5A1B',
    fontWeight: '600',
  },
  continueButton: {
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 32,
    borderRadius: 25,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueButtonActive: {
    backgroundColor: '#2D5A1B',
  },
  continueButtonDisabled: {
    backgroundColor: 'rgba(45,90,27,0.4)',
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
});
