import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#FAFAF8',
  },
  mainContent: {
    backgroundColor: '#FAFAF8',
  },
  headerGradient: {
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#D4A514',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  headerOrb1: {
    position: 'absolute',
    top: -40,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  headerOrb2: {
    position: 'absolute',
    top: 20,
    left: -80,
    width: 250,
    height: 120,
    borderRadius: 150,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: 'serif',
    fontSize: 18,
    fontWeight: '700',
    color: '#1A3A0F',
  },
  headerRight: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  content: {
    paddingBottom: 30,
  },
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 12,
    alignItems: 'center',
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  photoContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(245, 220, 50, 0.20)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
    shadowColor: 'rgba(184, 134, 11, 0.15)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: 'rgba(184, 134, 11, 0.30)',
  },
  initialsContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(245, 220, 50, 0.20)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(184, 134, 11, 0.30)',
  },
  initialsText: {
    fontSize: 28,
    fontWeight: '700',
    fontFamily: 'serif',
    color: '#2D5A1B',
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#2D5A1B',
    borderWidth: 2,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  nameEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  userName: {
    fontFamily: 'serif',
    fontSize: 20,
    fontWeight: '700',
    color: '#1A2E0F',
    textAlign: 'center',
  },
  nameInput: {
    fontFamily: 'serif',
    fontSize: 20,
    fontWeight: '700',
    color: '#1A2E0F',
    textAlign: 'center',
    borderBottomWidth: 1.5,
    borderBottomColor: '#2D5A1B',
    paddingBottom: 4,
    minWidth: 120,
  },
  editIcon: {
    marginLeft: 8,
  },
  subtitle: {
    fontSize: 13,
    color: '#888888',
    marginTop: 2,
  },
  badge: {
    backgroundColor: 'rgba(245, 220, 50, 0.18)',
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(184, 134, 11, 0.25)',
  },
  badgeText: {
    fontSize: 11,
    color: '#7A5800',
    fontWeight: '600',
  },
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    alignItems: 'center',
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  statNumber: {
    fontFamily: 'serif',
    fontSize: 22,
    fontWeight: '700',
    color: '#2D5A1B',
  },
  statsValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2D5A1B',
    fontFamily: 'serif',
  },
  statLabel: {
    fontSize: 11,
    color: '#7A9060',
    marginTop: 2,
  },
  menuContainer: {
    marginHorizontal: 16,
    marginTop: 12,
    gap: 8,
  },
  menuItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  menuIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  menuItemText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: '#1A2E0F',
  },
  logoutText: {
    color: '#E85555',
  },
  languageSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    shadowColor: '#2D5A1B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  languageSectionTitle: {
    fontFamily: 'serif',
    fontSize: 14,
    fontWeight: '700',
    color: '#2D5A1B',
    marginBottom: 12,
  },
  languageOptions: {
  },
  languageScrollContent: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 4,
  },
  languageOption: {
    minWidth: 100,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFAF8',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.06)',
    borderRadius: 10,
    paddingVertical: 10,
    gap: 6,
  },
  languageOptionActive: {
    backgroundColor: 'rgba(245, 220, 50, 0.15)',
    borderColor: '#D4A514',
  },
  languageFlag: {
    fontSize: 16,
  },
  languageLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#555555',
  },
  languageLabelActive: {
    fontWeight: '700',
    color: '#7A5800',
  },
  disclaimerText: {
    fontSize: 13,
    color: '#555555',
    lineHeight: 22,
    marginBottom: 20,
  },
  disclaimerSigned: {
    fontSize: 13,
    color: '#555555',
    fontStyle: 'italic',
    marginBottom: 24,
  },
  closeButton: {
    backgroundColor: '#2D5A1B',
    borderRadius: 25,
    paddingVertical: 14,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
